import Link from "next/link";
import type { Route } from "next";

export default function PrivacyPage() {
  return <main className="min-h-screen bg-slate-100 px-5 py-10"><article className="mx-auto max-w-3xl border border-slate-200 border-t-4 border-t-brand-government bg-white p-8 shadow-card"><p className="text-xs font-bold uppercase tracking-widest text-brand-government">Government User Access Management System</p><h1 className="mt-3 text-3xl font-bold text-brand-ink">Privacy and Acceptable-Use Notice</h1><p className="mt-4 border border-amber-300 bg-amber-50 p-4 text-sm leading-6 text-slate-700"><strong>Institutional approval required:</strong> the responsible government institution must confirm its official privacy contact and records-retention period before public rollout.</p>
    <section className="mt-7 space-y-3"><h2 className="text-xl font-bold text-brand-ink">Purpose of collection</h2><p className="text-sm leading-7 text-slate-700">Personal, employment, request, approval, and technical-processing information is collected to verify identity and official need, authorize access to government systems, fulfil approved account actions, communicate request status, maintain security, and provide an auditable official record.</p></section>
    <section className="mt-7 space-y-3"><h2 className="text-xl font-bold text-brand-ink">Access and disclosure</h2><p className="text-sm leading-7 text-slate-700">Information is available only according to assigned responsibilities: the applicant, the relevant Head of Department, authorized ICT officers, System Administrators, and authorized audit or oversight officers. It must not be used for unrelated purposes or shared through unauthorized channels.</p></section>
    <section className="mt-7 space-y-3"><h2 className="text-xl font-bold text-brand-ink">Accuracy and security</h2><p className="text-sm leading-7 text-slate-700">Users must provide accurate official information, protect credentials, sign out from shared devices, and promptly report suspected misuse. Decisions and administrative actions are recorded for accountability.</p></section>
    <section className="mt-7 space-y-3"><h2 className="text-xl font-bold text-brand-ink">Retention and enquiries</h2><p className="text-sm leading-7 text-slate-700">Records are retained according to the receiving institution's approved records schedule and applicable requirements. Requests for correction, access, or privacy assistance should be directed to the institution's designated ICT support and privacy contacts.</p></section>
    <p className="mt-8 border-t pt-5 text-sm"><Link href={"/signup" as Route} className="font-bold text-brand-government">Return to applicant registration</Link></p></article></main>;
}
